const char *strings[34][2] = {
    {"Diagnosi", "Test", },
    {"Ingressi", "Inputs", },
    {"Uscite", "Outputs", },
    {"Livello", "Level", },
    {"Calibrazione", "Calibrate", },
    {"Azzera litri", "Clear liters", },
    {"Azzera", "Clear", },
    {"Calda", "Hot", },
    {"Fredda", "Cold", },
    {"Scarico", "Drain", },
    {"Temperatura", "Temperature", },
    {"Gettoni", "Coins", },
    {"Linea", "Linea", },
    {"Totale", "Total", },
    {"Cassa", "Counter", },
    {"LED", "LEDS", },
    {"Spento", "Off", },
    {"Rosso", "Red", },
    {"Verde", "Green", },
    {"Blu", "Blue", },
    {"Giallo", "Yellow", },
    {"Violetto", "Purple", },
    {"Turchese", "Turquoise", },
    {"Bianco", "White", },
    {"Serratura", "Lock", },
    {"Aperto", "Open", },
    {"Chiuso", "Closed", },
    {"Apri", "Open", },
    {"Chiudi", "Close", },
    {"Chiavistello", "Bolt", },
    {"Digitale", "Digital", },
    {"Meccanica", "Mechanical", },
    {"Cesto", "Drum", },
    {"Oblo'", "Porthole", },
};

