const char *strings[157][2] = {
    {"Diagnosi", "Test", },
    {"Ingressi", "Inputs", },
    {"Uscite", "Outputs", },
    {"Livello", "Level", },
    {"Calibrazione", "Calibrate", },
    {"Azzera litri", "Clear liters", },
    {"Azzera", "Clear", },
    {"Calda", "Hot", },
    {"Fredda", "Cold", },
    {"Ammollo", "Soaking", },
    {"Prelavaggio", "Prewash", },
    {"Lavaggio", "Wash", },
    {"Risciacquo", "Flushing", },
    {"Centrifuga", "Centrifuge", },
    {"Srotolamento", "Unrolling", },
    {"Attesa operatore", "Waiting", },
    {"Scarico", "Drain", },
    {"Temperatura", "Temperature", },
    {"Gettoni", "Coins", },
    {"Linea", "Linea", },
    {"Totale", "Total", },
    {"Cassa", "Counter", },
    {"LED", "LEDS", },
    {"Spento", "Off", },
    {"Rosso", "Red", },
    {"Verde", "Green", },
    {"Blu", "Blue", },
    {"Giallo", "Yellow", },
    {"Violetto", "Purple", },
    {"Turchese", "Turquoise", },
    {"Bianco", "White", },
    {"Serratura", "Lock", },
    {"Aperto", "Open", },
    {"Chiuso", "Closed", },
    {"Apri", "Open", },
    {"Chiudi", "Close", },
    {"Chiavistello", "Bolt", },
    {"Digitale", "Digital", },
    {"Meccanica", "Mechanical", },
    {"Motore avanti", "Motor forward", },
    {"Motore indietro", "Motor back", },
    {"Oblo'", "Porthole", },
    {"Archiviazione", "Archiving", },
    {"Impostazioni", "Settings", },
    {"Chiavetta", "USB Drive", },
    {"Errore di comunicazione", "Communication error", },
    {"Riprova", "Retry", },
    {"Importa una configurazione", "Import configuration", },
    {"Esporta la configurazione", "Export configuration", },
    {"Nessuna configurazione trovata", "No configuration found", },
    {"Operazione fallita", "Operation failed", },
    {"Operazione conclusa con successo", "Operation successful", },
    {"Scelta programma", "Program choice", },
    {"Errore EEPROM", "EEPROM error", },
    {"Allarme spegnimento", "Power off alarm", },
    {"Allarme comunicazione", "Communication alarm", },
    {"OBLO' APERTO", "PORTHOLE OPEN", },
    {"OBLO' SBLOCCATO", "PORTHOLE UNLOCKED", },
    {"STOP EMERGENZA", "EMERGENCY STOP", },
    {"SBILANCIAMENTO", "UNBALANCING", },
    {"CHIAVISTELLO BLOCCATO", "BOLT LOCKED", },
    {"ALLARME SERRATURA", "LOCK ALARM", },
    {"ALLARME LIVELLO", "LEVEL ALARM", },
    {"SERRATURA FORZATA", "LOCK FORCED", },
    {"NO TEMPERATURA", "NO TEMPERATURE", },
    {"INVERTER KO", "INVERTER KO", },
    {"FILTRO APERTO", "FILTER OPEN", },
    {"BLOCCO BRUCIATORE", "BURNER BLOCK", },
    {"ALLARME SONDA TEMPERATURA", "TEMPERATURE PROBE ALARM", },
    {"APERTO CON H2O", "OPEN WITH H2O", },
    {"ALLARME ACCELEROMETRO", "ACCELEROMETER ALARM", },
    {"ACCELEROMETRO FUORI SCALA", "ACCELEROMETER OFF SCALE", },
    {"ALLARME VELOCITA'", "SPEED ALARM", },
    {"NO MOTO", "NO MOTION", },
    {"NO FERMO", "NO STOP", },
    {"ALLARME TEMPERATURA", "TEMPERATURE ALARM", },
    {"H2O IN VASCA", "H2O IN TANK", },
    {"ALLARME RIEMPIMENTO", "FILLING ALARM", },
    {"ALLARME RISCALDAMENTO", "HEAT ALARM", },
    {"ALLARME SCARICO", "DRAIN ALARM", },
    {"Pagare alla cassa", "Pay at the counter", },
    {"Inserire gettone", "Insert token", },
    {"Inserire monete", "Insert coin", },
    {"MACCHINA ACCESA", "MACHINE ON", },
    {"FINE LAVAGGIO", "CYCLE END", },
    {"INIZIO LAVAGGIO", "CYCLE START", },
    {"LAVAGGIO INTERROTTO", "CYCLE STOPPED", },
    {"APRIRE OBLO", "OPEN PORT", },
    {"STANDBY SAPONI", "DETERGENT STANDBY", },
    {"Allarme", "Alarm", },
    {"Parametri", "Parameters", },
    {"Pausa lavaggio", "Cycle pause", },
    {"Scarico necessario; tenere premuto il tasto stop", "Drain required; long press the stop button", },
    {"Precarica in corso", "Preloading", },
    {"Attesa livel. e temp.", "Wait for temper/level", },
    {"Attesa livello", "Waiting for the water level", },
    {"Attesa temperatura", "Waiting for temperature", },
    {"Riempimento", "Filling up", },
    {"Att.termodegradazione", "Wait for thermal down", },
    {"Attesa livel. scarico", "Wait for drain level", },
    {"Prescarico", "Pre-draining", },
    {"Preparazione", "Preparing", },
    {"Attesa velocita'", "Warning speed", },
    {"In frenata a causa di uno sbilanciamento", "Stopping due to lurching", },
    {"Attesa frenata", "Waiting for full stop", },
    {"Scarico forzato", "Forced drain", },
    {"Recupero", "Recovery", },
    {"Uscita lavaggio", "Washing exit", },
    {"Programmi", "Programs", },
    {"Codice", "Code", },
    {"In marcia", "Running", },
    {"Abilita", "Enable", },
    {"Disabilita", "Disable", },
    {"Informazioni", "Info", },
    {"Cancellare il programma?", "Delete the program?", },
    {"Cancellare il passo?", "Delete the step?", },
    {"Avanzate", "Advanced", },
    {"Comunicazione", "Communication", },
    {"Ripristino a impostazioni di fabbrica", "Factory reset", },
    {"Accesso", "Access", },
    {"Molto sporchi con prelavaggio", "Very dirty with prewash", },
    {"Medio sporchi con prelavaggio", "Average dirty with prewash", },
    {"Molto sporchi", "Very dirty", },
    {"Medio sporchi", "Average dirty", },
    {"Colorati", "Colored", },
    {"Sintetici", "Synthetic", },
    {"Piumoni", "Duvets", },
    {"Delicati a freddo", "Cold for delicates", },
    {"Lana", "Wool", },
    {"Lino e tendaggi", "Linen and curtains", },
    {"Solo centrifuga (1000 giri)", "Centrifuge only (1000 rpm)", },
    {"Solo centrifuga (600 giri)", "Centrifuge only (600 rpm)", },
    {"Sanificazione", "Sanification", },
    {"Prelavaggio con centrifuga", "Prewash with centrifuge", },
    {"Risciacquo con centrifuga", "Flushing with centrifuge", },
    {"Nuovo passo", "New step", },
    {"Delicato", "Delicate", },
    {"Energico", "Energetic", },
    {"Accelerometro", "Accelerometer", },
    {"Aggiorna", "Update", },
    {"Aggiornamento firmware concluso, resettare il dispositivo", "Firmware update successful, reset the device", },
    {"Aggiornamento firmware in corso", "Firmware update in progress", },
    {"Aggiornamento firmware fallito", "Firmware update failed ", },
    {"Prezzo", "Price", },
    {"Lavaggio concluso: aprire l'oblo' e' recuperare gli indumenti", "Washing cycle done: open the porthole and retrieve the clothes", },
    {"Ora/data", "Time/date", },
    {"Lavaggio programmato", "Programmed wash cycle", },
    {"Ore", "Hours", },
    {"Minuti", "Minutes", },
    {"Giorno", "Day", },
    {"Mese", "Month", },
    {"Anno", "Year", },
    {"Rinomina macchina", "Rename machine", },
    {"Velocita'", "Speed", },
    {"Durata", "Duration", },
    {"Password", "Password", },
    {"Sapone", "Detergent", },
};

