#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_DIAGNOSI = 0,
    STRINGS_INGRESSI,
    STRINGS_USCITE,
    STRINGS_LIVELLO,
    STRINGS_CALIBRAZIONE,
    STRINGS_AZZERA_LITRI,
    STRINGS_AZZERA,
    STRINGS_CALDA,
    STRINGS_FREDDA,
    STRINGS_SCARICO,
    STRINGS_TEMPERATURA,
    STRINGS_GETTONI,
    STRINGS_LINEA,
    STRINGS_TOTALE,
    STRINGS_CASSA,
    STRINGS_LED,
    STRINGS_SPENTO,
    STRINGS_ROSSO,
    STRINGS_VERDE,
    STRINGS_BLU,
    STRINGS_GIALLO,
    STRINGS_VIOLETTO,
    STRINGS_TURCHESE,
    STRINGS_BIANCO,
    STRINGS_SERRATURA,
    STRINGS_APERTO,
    STRINGS_CHIUSO,
    STRINGS_APRI,
    STRINGS_CHIUDI,
    STRINGS_CHIAVISTELLO,
    STRINGS_DIGITALE,
    STRINGS_MECCANICA,
    STRINGS_CESTO,
    STRINGS_OBLO,
} strings_t;

extern const char *strings[34][2];

#endif
