const char *strings[82][2] = {
    {"Diagnosi", "Test", },
    {"Ingressi", "Inputs", },
    {"Uscite", "Outputs", },
    {"Livello", "Level", },
    {"Calibrazione", "Calibrate", },
    {"Azzera litri", "Clear liters", },
    {"Azzera", "Clear", },
    {"Calda", "Hot", },
    {"Fredda", "Cold", },
    {"Scarico", "Drain", },
    {"Temperatura", "Temperature", },
    {"Gettoni", "Coins", },
    {"Linea", "Linea", },
    {"Totale", "Total", },
    {"Cassa", "Counter", },
    {"LED", "LEDS", },
    {"Spento", "Off", },
    {"Rosso", "Red", },
    {"Verde", "Green", },
    {"Blu", "Blue", },
    {"Giallo", "Yellow", },
    {"Violetto", "Purple", },
    {"Turchese", "Turquoise", },
    {"Bianco", "White", },
    {"Serratura", "Lock", },
    {"Aperto", "Open", },
    {"Chiuso", "Closed", },
    {"Apri", "Open", },
    {"Chiudi", "Close", },
    {"Chiavistello", "Bolt", },
    {"Digitale", "Digital", },
    {"Meccanica", "Mechanical", },
    {"Cesto", "Drum", },
    {"Oblo'", "Porthole", },
    {"Archiviazione", "Archiving", },
    {"Impostazioni", "Settings", },
    {"Chiavetta", "USB Drive", },
    {"Errore di comunicazione", "Communication error", },
    {"Riprova", "Retry", },
    {"Importa una configurazione", "Import configuration", },
    {"Nessuna configurazione trovata", "No configuration found", },
    {"Operazione fallita", "Operation failed", },
    {"Operazione conclusa con successo", "Operation successful", },
    {"Scelta programma", "Program choice", },
    {"Errore EEPROM", "EEPROM error", },
    {"Allarme spegnimento", "Power off alarm", },
    {"Allarme comunicazione", "Communication alarm", },
    {"OBLO' APERTO", "PORTHOLE OPEN", },
    {"OBLO' SBLOCCATO", "PORTHOLE UNLOCKED", },
    {"STOP EMERGENZA", "EMERGENCY STOP", },
    {"SBILANCIAMENTO", "UNBALANCING", },
    {"CHIAVISTELLO BLOCCATO", "BOLT LOCKED", },
    {"ALLARME SERRATURA", "LOCK ALARM", },
    {"ALLARME LIVELLO", "LEVEL ALARM", },
    {"SERRATURA FORZATA", "LOCK FORCED", },
    {"NO TEMPERATURA", "NO TEMPERATURE", },
    {"INVERTER KO", "INVERTER KO", },
    {"FILTRO APERTO", "FILTER OPEN", },
    {"BLOCCO BRUCIATORE", "BURNER BLOCK", },
    {"ALLARME SONDA TEMPERATURA", "TEMPERATURE PROBE ALARM", },
    {"APERTO CON H2O", "OPEN WITH H2O", },
    {"ALLARME ACCELEROMETRO", "ACCELEROMETER ALARM", },
    {"ACCELEROMETRO FUORI SCALA", "ACCELEROMETER OFF SCALE", },
    {"ALLARME VELOCITA'", "SPEED ALARM", },
    {"NO MOTO", "NO MOTION", },
    {"NO FERMO", "NO STOP", },
    {"ALLARME TEMPERATURA", "TEMPERATURE ALARM", },
    {"H2O IN VASCA", "H2O IN TANK", },
    {"ALLARME RIEMPIMENTO", "FILLING ALARM", },
    {"ALLARME RISCALDAMENTO", "HEAT ALARM", },
    {"ALLARME SCARICO", "DRAIN ALARM", },
    {"Pagare alla cassa", "Pay at the counter", },
    {"Inserire gettone", "Insert token", },
    {"Inserire monete", "Insert coin", },
    {"MACCHINA ACCESA", "MACHINE ON", },
    {"FINE LAVAGGIO", "CYCLE END", },
    {"INIZIO LAVAGGIO", "CYCLE START", },
    {"LAVAGGIO INTERROTTO", "CYCLE STOPPED", },
    {"APRIRE OBLO", "OPEN PORT", },
    {"STANDBY SAPONI", "DETERGENT STANDBY", },
    {"Allarme", "Alarm", },
    {"Parametri", "Parameters", },
};

